import Link from "next/link";

export type CountBucket = { label: string | null; count: number | null };
export type KevCve = { cve_id: string; title: string | null; product: string | null; epss_score: number | null; cvss_score: number | null; severity: string | null; required_action: string | null; due_date: string | null };
export type TopEpssCve = { cve_id: string; title: string | null; epss_score: number | null; epss_percentile: number | null };
export type Stats = {
  total_cves?: number | null; total_products?: number | null; latest_release?: string | null; exploited_count?: number | null; publicly_disclosed_count?: number | null;
  total_kev_vulnerabilities?: number | null; average_epss_score?: number | null; average_cvss_score?: number | null; highest_epss_score?: number | null; epss_enriched_cves?: number | null; epss_at_least_10_percent?: number | null;
  nvd_enriched_cves?: number | null; impact_known_cves?: number | null; critical_cves?: number | null; immediate_action_count?: number | null; high_priority_count?: number | null; routine_count?: number | null;
  cves_by_severity?: CountBucket[] | null; cves_by_release?: CountBucket[] | null; cves_by_impact?: CountBucket[] | null; kev_distribution?: CountBucket[] | null; cvss_score_distribution?: CountBucket[] | null;
  top_epss_cves?: TopEpssCve[] | null; kev_cves?: KevCve[] | null;
};

type Tone = "blue" | "red" | "orange" | "purple" | "green" | "yellow";

const toneStyles: Record<Tone, { text: string; bg: string; bgSoft: string; border: string; fill: string; shadow: string }> = {
  blue: { text: "text-cyan-200", bg: "bg-cyan-400", bgSoft: "bg-cyan-400/70", border: "border-cyan-300/35", fill: "#38bdf8", shadow: "shadow-cyan-500/10" },
  red: { text: "text-rose-200", bg: "bg-rose-400", bgSoft: "bg-rose-400/70", border: "border-rose-300/35", fill: "#fb7185", shadow: "shadow-rose-500/10" },
  orange: { text: "text-orange-200", bg: "bg-orange-400", bgSoft: "bg-orange-400/70", border: "border-orange-300/35", fill: "#fb923c", shadow: "shadow-orange-500/10" },
  purple: { text: "text-violet-200", bg: "bg-violet-400", bgSoft: "bg-violet-400/70", border: "border-violet-300/35", fill: "#a78bfa", shadow: "shadow-violet-500/10" },
  green: { text: "text-emerald-200", bg: "bg-emerald-400", bgSoft: "bg-emerald-400/70", border: "border-emerald-300/35", fill: "#34d399", shadow: "shadow-emerald-500/10" },
  yellow: { text: "text-amber-200", bg: "bg-amber-300", bgSoft: "bg-amber-300/70", border: "border-amber-300/35", fill: "#facc15", shadow: "shadow-amber-500/10" },
};

const severityColors: Record<string, string> = { Critical: "#fb7185", Important: "#fb923c", High: "#fb923c", Moderate: "#facc15", Low: "#22c55e", Unknown: "#64748b", None: "#64748b" };
const palette = ["#38bdf8", "#a78bfa", "#f472b6", "#2dd4bf", "#facc15", "#fb923c", "#34d399"];
export const emptyStats: Stats = { total_cves: 0, total_products: 0, latest_release: null, exploited_count: 0, publicly_disclosed_count: 0, total_kev_vulnerabilities: 0, average_epss_score: null, average_cvss_score: null, highest_epss_score: null, epss_enriched_cves: 0, epss_at_least_10_percent: 0, nvd_enriched_cves: 0, impact_known_cves: 0, critical_cves: 0, immediate_action_count: 0, high_priority_count: 0, routine_count: 0, cves_by_severity: [], cves_by_release: [], cves_by_impact: [], kev_distribution: [], cvss_score_distribution: [], top_epss_cves: [], kev_cves: [] };

export function safeNumber(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) ? value : 0; }
export function formatCount(value: number | null | undefined) { return safeNumber(value).toLocaleString("en-US"); }
export function formatPct(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) ? `${(value * 100).toFixed(1)}%` : "—"; }
export function formatCvss(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) ? value.toFixed(1) : "—"; }
function normalizeBuckets(buckets: CountBucket[] | null | undefined) { return (buckets ?? []).map((bucket) => ({ label: bucket?.label ?? "Unknown", count: safeNumber(bucket?.count) })); }
function formatTruncated(value: string | null | undefined, maxLength = 78) { return !value ? "—" : value.length > maxLength ? `${value.slice(0, maxLength).trimEnd()}…` : value; }
function colorFor(label: string, index: number) { return severityColors[label] ?? palette[index % palette.length]; }

function Sparkline({ tone }: { tone: Tone }) {
  return <div className="mt-3 flex h-8 items-end gap-1.5 opacity-80">{[36, 54, 43, 74, 58, 88, 69, 94].map((height, index) => <span key={index} className={`w-full rounded-t-sm ${toneStyles[tone].bgSoft}`} style={{ height: `${height}%` }} />)}</div>;
}

export function KpiCard({ label, value, helper, href, tone = "blue" }: { label: string; value: string; helper: string; href: string; tone?: Tone }) {
  const styles = toneStyles[tone];
  return <Link href={href} className={`soc-card group block min-h-36 cursor-pointer border ${styles.border} ${styles.shadow} transition hover:-translate-y-0.5 hover:bg-slate-900/85`}><div className="flex items-start justify-between gap-3"><p className="text-[0.66rem] font-bold uppercase tracking-[0.22em] text-slate-500">{label}</p><span className={`h-2.5 w-2.5 rounded-full ${styles.bg} shadow-[0_0_18px_currentColor]`} /></div><p className={`mt-3 text-3xl font-black tabular-nums ${styles.text}`}>{value}</p><p className="mt-1 min-h-9 text-xs leading-5 text-slate-400">{helper}</p><Sparkline tone={tone} /></Link>;
}

export function DonutChart({ title, buckets, param }: { title: string; buckets: CountBucket[] | null | undefined; param: string }) {
  const rows = normalizeBuckets(buckets); const total = rows.reduce((sum, row) => sum + row.count, 0); let cursor = 0;
  const gradient = total > 0 ? rows.map((row, index) => { const start = cursor; const size = (row.count / total) * 100; cursor += size; return `${colorFor(row.label, index)} ${start}% ${cursor}%`; }).join(", ") : "#334155 0% 100%";
  return <section className="soc-card"><h2 className="panel-title">{title}</h2><div className="mt-5 grid gap-5 sm:grid-cols-[10rem_1fr] sm:items-center"><Link aria-label={`${title} details`} href="/cves" className="relative grid h-40 w-40 place-items-center rounded-full shadow-2xl shadow-cyan-950/30" style={{ background: `conic-gradient(${gradient})` }}><div className="grid h-24 w-24 place-items-center rounded-full border border-slate-700/80 bg-[#06101f] text-center"><span className="text-2xl font-black tabular-nums">{formatCount(total)}</span><span className="-mt-6 text-[0.62rem] uppercase tracking-[0.2em] text-slate-500">CVEs</span></div></Link><div className="space-y-2">{rows.length === 0 || total === 0 ? <p className="empty-state">No chart data available.</p> : rows.map((row, index) => <Link href={`/cves?${param}=${encodeURIComponent(row.label)}`} key={row.label} className="grid grid-cols-[0.75rem_1fr_auto] items-center gap-2 rounded-lg px-2 py-1.5 text-sm hover:bg-cyan-400/10"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: colorFor(row.label, index) }} /><span className="truncate text-slate-300">{row.label}</span><span className="font-bold tabular-nums text-slate-100">{formatCount(row.count)}</span></Link>)}</div></div></section>;
}

export function BarChart({ title, buckets, param = "", tone = "blue" }: { title: string; buckets: CountBucket[] | null | undefined; param?: string; tone?: Tone }) {
  const rows = normalizeBuckets(buckets).slice(0, 12); const max = Math.max(...rows.map((row) => row.count), 0); const styles = toneStyles[tone];
  return <section className="soc-card"><h2 className="panel-title">{title}</h2><div className="mt-5 flex h-60 items-end gap-2 border-b border-l border-slate-700/70 px-2 pb-2">{rows.length === 0 || max === 0 ? <p className="empty-state w-full self-center">No chart data available.</p> : rows.map((row) => { const height = Math.max((row.count / max) * 100, 5); const bar = <><span className="mb-2 text-[0.65rem] font-semibold text-slate-400">{formatCount(row.count)}</span><span className={`w-full rounded-t-md ${styles.bgSoft} shadow-lg ${styles.shadow}`} style={{ height: `${height}%` }} /><span className="mt-2 h-8 w-full truncate text-center text-[0.62rem] text-slate-400" title={row.label}>{row.label}</span></>; return param ? <Link href={`/cves?${param}=${encodeURIComponent(row.label)}`} key={row.label} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end rounded-md px-1 hover:bg-cyan-400/10">{bar}</Link> : <div key={row.label} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end px-1">{bar}</div>; })}</div></section>;
}

function ActionRow({ label, value, tone, href }: { label: string; value: number | null | undefined; tone: string; href?: string }) { const content = <><span className="text-slate-300">{label}</span><span className={`text-lg font-black tabular-nums ${tone}`}>{formatCount(value)}</span></>; return href ? <Link href={href} className="flex cursor-pointer items-center justify-between rounded-xl border border-slate-800/70 bg-slate-950/60 px-3 py-2 transition hover:border-cyan-400/30 hover:bg-cyan-400/10">{content}</Link> : <div className="flex items-center justify-between rounded-xl border border-slate-800/70 bg-slate-950/60 px-3 py-2">{content}</div>; }
function Coverage({ label, value, helper }: { label: string; value: number | null; helper: string }) { const pct = value == null ? 0 : Math.max(0, Math.min(value * 100, 100)); return <div><div className="flex justify-between text-sm"><span className="text-slate-300">{label}</span><span className="font-bold text-emerald-200">{value == null ? "—" : `${pct.toFixed(1)}%`}</span></div><div className="mt-2 h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-400 shadow-[0_0_14px_rgba(52,211,153,0.55)]" style={{ width: `${pct}%` }} /></div><p className="mt-1 text-xs text-slate-500">{helper}</p></div>; }
export function RiskPanel({ stats }: { stats: Stats }) { const total = safeNumber(stats.total_cves); const withoutNvd = Math.max(total - safeNumber(stats.nvd_enriched_cves), 0); return <aside className="space-y-4"><section className="soc-card"><h2 className="panel-title">Immediate Actions</h2><div className="mt-4 space-y-3"><ActionRow href="/cves?severity=Critical" label="Critical CVEs" value={stats.critical_cves} tone="text-rose-300" /><ActionRow href="/cves?epss=high" label="High EPSS CVEs" value={stats.epss_at_least_10_percent} tone="text-orange-300" /><ActionRow href="/kev" label="KEV vulnerabilities" value={stats.total_kev_vulnerabilities} tone="text-violet-300" /><ActionRow href="/cves?nvd=missing" label="Missing NVD coverage" value={withoutNvd} tone="text-cyan-300" /></div></section><CoveragePanel stats={stats} /></aside>; }
export function CoveragePanel({ stats }: { stats: Stats }) { const total = safeNumber(stats.total_cves); const epssCoverage = total > 0 ? safeNumber(stats.epss_enriched_cves) / total : null; const nvdCoverage = total > 0 ? safeNumber(stats.nvd_enriched_cves) / total : null; const impactCoverage = total > 0 ? safeNumber(stats.impact_known_cves) / total : null; return <section className="soc-card"><h2 className="panel-title">Enrichment Coverage</h2><div className="mt-4 space-y-4"><Coverage label="EPSS coverage" value={epssCoverage} helper={`${formatCount(stats.epss_enriched_cves)} EPSS-enriched CVEs`} /><Coverage label="NVD coverage" value={nvdCoverage} helper={`${formatCount(stats.nvd_enriched_cves)} NVD-enriched CVEs`} /><Coverage label="Impact coverage" value={impactCoverage} helper={`${formatCount(stats.impact_known_cves)} CVEs with known impact`} /><ActionRow label="CISA KEV matches" value={stats.total_kev_vulnerabilities} tone="text-violet-300" /></div></section>; }
export function TopEpssTable({ cves }: { cves: TopEpssCve[] | null | undefined }) { const rows = cves ?? []; return <section className="soc-card"><h2 className="panel-title">Top CVEs by EPSS Score</h2>{rows.length === 0 ? <p className="empty-state mt-4">No EPSS-ranked CVEs available.</p> : <div className="mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>CVE</th><th>Title</th><th>EPSS score</th><th>Percentile</th></tr></thead><tbody>{rows.map((cve) => <tr key={cve.cve_id}><td><Link className="link" href={`/cves/${cve.cve_id}`}>{cve.cve_id}</Link></td><td>{cve.title ?? "Untitled"}</td><td>{formatPct(cve.epss_score)}</td><td>{formatPct(cve.epss_percentile)}</td></tr>)}</tbody></table></div>}</section>; }
export function KevTable({ cves }: { cves: KevCve[] | null | undefined }) { const rows = cves ?? []; return <section className="soc-card"><h2 className="panel-title">Known Exploited Vulnerabilities</h2>{rows.length === 0 ? <p className="empty-state mt-4">No CISA KEV CVEs are available.</p> : <div className="mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>CVE</th><th>Product</th><th>Severity</th><th>EPSS</th><th>CVSS</th><th>Required action</th><th>Due date</th></tr></thead><tbody>{rows.map((cve) => <tr key={cve.cve_id}><td><Link className="link" href={`/cves/${cve.cve_id}`}>{cve.cve_id}</Link></td><td>{cve.product ?? "Unknown"}</td><td>{cve.severity ?? "Unknown"}</td><td>{formatPct(cve.epss_score)}</td><td>{formatCvss(cve.cvss_score)}</td><td title={cve.required_action ?? undefined}>{formatTruncated(cve.required_action)}</td><td>{cve.due_date ?? "—"}</td></tr>)}</tbody></table></div>}</section>; }
