import Link from "next/link";

export type CountBucket = { label: string | null; count: number | null };
export type KevCve = { cve_id: string; title: string | null; product: string | null; epss_score: number | null; cvss_score: number | null; severity: string | null; required_action: string | null; due_date: string | null };
export type TopEpssCve = { cve_id: string; title: string | null; epss_score: number | null; epss_percentile: number | null };
export type Stats = {
  total_cves?: number | null; total_products?: number | null; latest_release?: string | null; exploited_count?: number | null; publicly_disclosed_count?: number | null;
  total_kev_vulnerabilities?: number | null; average_epss_score?: number | null; average_cvss_score?: number | null; highest_epss_score?: number | null; epss_enriched_cves?: number | null; epss_at_least_10_percent?: number | null;
  nvd_enriched_cves?: number | null; impact_known_cves?: number | null; critical_cves?: number | null; immediate_action_count?: number | null; high_priority_count?: number | null; routine_count?: number | null;
  cves_by_severity?: CountBucket[] | null; cves_by_release?: CountBucket[] | null; cves_by_impact?: CountBucket[] | null; kev_distribution?: CountBucket[] | null; cvss_score_distribution?: CountBucket[] | null;
  top_epss_cves?: TopEpssCve[] | null; kev_cves?: KevCve[] | null;
};

const severityColors: Record<string, string> = { Critical: "#fb7185", Important: "#fb923c", High: "#fb923c", Moderate: "#facc15", Low: "#22c55e", Unknown: "#64748b" };
export const emptyStats: Stats = { total_cves: 0, total_products: 0, latest_release: null, exploited_count: 0, publicly_disclosed_count: 0, total_kev_vulnerabilities: 0, average_epss_score: null, average_cvss_score: null, highest_epss_score: null, epss_enriched_cves: 0, epss_at_least_10_percent: 0, nvd_enriched_cves: 0, impact_known_cves: 0, critical_cves: 0, immediate_action_count: 0, high_priority_count: 0, routine_count: 0, cves_by_severity: [], cves_by_release: [], cves_by_impact: [], kev_distribution: [], cvss_score_distribution: [], top_epss_cves: [], kev_cves: [] };

export function safeNumber(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) ? value : 0; }
export function formatCount(value: number | null | undefined) { return safeNumber(value).toLocaleString("en-US"); }
export function formatPct(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) ? `${(value * 100).toFixed(1)}%` : "—"; }
export function formatCvss(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) ? value.toFixed(1) : "—"; }
function normalizeBuckets(buckets: CountBucket[] | null | undefined) { return (buckets ?? []).map((bucket) => ({ label: bucket?.label ?? "Unknown", count: safeNumber(bucket?.count) })); }
function formatTruncated(value: string | null | undefined, maxLength = 90) { return !value ? "—" : value.length > maxLength ? `${value.slice(0, maxLength).trimEnd()}…` : value; }

function Sparkline() { return <div className="mt-4 flex h-8 items-end gap-1 opacity-70">{[30, 55, 42, 76, 61, 88, 70].map((height, index) => <span key={index} className="w-full rounded-t bg-cyan-300/50" style={{ height: `${height}%` }} />)}</div>; }
export function KpiCard({ label, value, helper, href, tone = "text-white" }: { label: string; value: string; helper: string; href: string; tone?: string }) { return <Link href={href} className="card group block cursor-pointer bg-gradient-to-br from-slate-900 to-slate-950 transition hover:-translate-y-1 hover:border-cyan-300/40 hover:shadow-cyan-950/30"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-slate-500">{label}</p><p className={`mt-3 text-3xl font-black ${tone}`}>{value}</p><p className="mt-2 text-sm text-slate-400">{helper}</p><Sparkline /></Link>; }
export function DonutChart({ title, buckets, param }: { title: string; buckets: CountBucket[] | null | undefined; param: string }) { const rows = normalizeBuckets(buckets); const total = rows.reduce((sum, row) => sum + row.count, 0); let cursor = 0; const gradient = total > 0 ? rows.map((row, index) => { const start = cursor; const size = (row.count / total) * 100; cursor += size; const color = severityColors[row.label] ?? ["#38bdf8", "#a78bfa", "#f472b6", "#2dd4bf"][index % 4]; return `${color} ${start}% ${cursor}%`; }).join(", ") : "#334155 0% 100%"; return <section className="card"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-5 flex flex-col items-center gap-5 sm:flex-row"><div className="grid h-40 w-40 place-items-center rounded-full" style={{ background: `conic-gradient(${gradient})` }}><div className="grid h-24 w-24 place-items-center rounded-full bg-slate-950 text-center"><span className="text-2xl font-bold">{formatCount(total)}</span></div></div><div className="w-full space-y-2">{rows.length === 0 || total === 0 ? <p className="empty-state">No chart data available.</p> : rows.map((row) => <Link href={`/cves?${param}=${encodeURIComponent(row.label)}`} key={row.label} className="flex items-center justify-between gap-3 rounded-lg px-2 py-1 text-sm hover:bg-slate-800"><span className="truncate text-slate-300">{row.label}</span><span className="font-semibold">{formatCount(row.count)}</span></Link>)}</div></div><Link className="mt-4 inline-block text-sm font-semibold text-cyan-300 hover:underline" href="/cves">View details</Link></section>; }
export function BarChart({ title, buckets, horizontal = false, valueFormatter = formatCount, param = "" }: { title: string; buckets: CountBucket[] | null | undefined; horizontal?: boolean; valueFormatter?: (value: number) => string; param?: string }) { const rows = normalizeBuckets(buckets); const max = Math.max(...rows.map((row) => row.count), 0); return <section className="card"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-5 space-y-3">{rows.length === 0 || max === 0 ? <p className="empty-state">No chart data available.</p> : rows.slice(0, horizontal ? 20 : 10).map((row) => { const content = <><span className="truncate text-slate-300">{row.label}</span><div className="h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${Math.max((row.count / max) * 100, 3)}%` }} /></div><span className="font-semibold text-slate-100 sm:text-right">{valueFormatter(row.count)}</span></>; return param ? <Link href={`/cves?${param}=${encodeURIComponent(row.label)}`} key={row.label} className="grid gap-2 rounded-lg text-sm hover:bg-slate-800 sm:grid-cols-[9rem_1fr_4rem] sm:items-center">{content}</Link> : <div key={row.label} className="grid gap-2 text-sm sm:grid-cols-[9rem_1fr_4rem] sm:items-center">{content}</div>; })}</div><Link className="mt-4 inline-block text-sm font-semibold text-cyan-300 hover:underline" href="/cves">View details</Link></section>; }
function ActionRow({ label, value, tone, href }: { label: string; value: number | null | undefined; tone: string; href?: string }) { const content = <><span className="text-slate-300">{label}</span><span className={`text-xl font-bold ${tone}`}>{formatCount(value)}</span></>; return href ? <Link href={href} className="flex cursor-pointer items-center justify-between rounded-lg bg-slate-950/70 px-3 py-2 transition hover:bg-slate-800/80">{content}</Link> : <div className="flex items-center justify-between rounded-lg bg-slate-950/70 px-3 py-2">{content}</div>; }
function Coverage({ label, value, helper }: { label: string; value: number | null; helper: string }) { const pct = value == null ? 0 : Math.max(0, Math.min(value * 100, 100)); return <div><div className="flex justify-between text-sm"><span className="text-slate-300">{label}</span><span className="font-semibold">{value == null ? "—" : `${pct.toFixed(1)}%`}</span></div><div className="mt-2 h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-violet-400" style={{ width: `${pct}%` }} /></div><p className="mt-1 text-xs text-slate-500">{helper}</p></div>; }
export function RiskPanel({ stats }: { stats: Stats }) { const total = safeNumber(stats.total_cves); const epssCoverage = total > 0 ? safeNumber(stats.epss_enriched_cves) / total : null; const nvdCoverage = total > 0 ? safeNumber(stats.nvd_enriched_cves) / total : null; const impactCoverage = total > 0 ? safeNumber(stats.impact_known_cves) / total : null; const withoutNvd = Math.max(total - safeNumber(stats.nvd_enriched_cves), 0); return <aside className="space-y-4"><section className="card"><h2 className="text-lg font-semibold">Immediate Actions</h2><div className="mt-4 space-y-3"><ActionRow href="/cves?severity=Critical" label="Critical CVEs" value={stats.critical_cves} tone="text-rose-300" /><ActionRow href="/cves?epss=high" label="High EPSS CVEs" value={stats.epss_at_least_10_percent} tone="text-orange-300" /><ActionRow href="/kev" label="KEV vulnerabilities" value={stats.total_kev_vulnerabilities} tone="text-fuchsia-300" /><ActionRow href="/cves?nvd=missing" label="Missing NVD coverage" value={withoutNvd} tone="text-cyan-300" /></div></section><CoveragePanel stats={stats} /></aside>; }
export function CoveragePanel({ stats }: { stats: Stats }) { const total = safeNumber(stats.total_cves); const epssCoverage = total > 0 ? safeNumber(stats.epss_enriched_cves) / total : null; const nvdCoverage = total > 0 ? safeNumber(stats.nvd_enriched_cves) / total : null; const impactCoverage = total > 0 ? safeNumber(stats.impact_known_cves) / total : null; return <section className="card"><h2 className="text-lg font-semibold">Enrichment Coverage</h2><div className="mt-4 space-y-4"><Coverage label="EPSS coverage" value={epssCoverage} helper={`${formatCount(stats.epss_enriched_cves)} EPSS-enriched CVEs`} /><Coverage label="NVD coverage" value={nvdCoverage} helper={`${formatCount(stats.nvd_enriched_cves)} NVD-enriched CVEs`} /><Coverage label="Impact coverage" value={impactCoverage} helper={`${formatCount(stats.impact_known_cves)} CVEs with known impact`} /><ActionRow label="CISA KEV matches" value={stats.total_kev_vulnerabilities} tone="text-fuchsia-300" /></div></section>; }
export function TopEpssTable({ cves }: { cves: TopEpssCve[] | null | undefined }) { const rows = cves ?? []; return <section className="card"><h2 className="text-lg font-semibold">Top CVEs by EPSS</h2>{rows.length === 0 ? <p className="empty-state mt-4">No EPSS-ranked CVEs available.</p> : <div className="mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>CVE</th><th>Title</th><th>EPSS score</th><th>Percentile</th></tr></thead><tbody>{rows.map((cve) => <tr key={cve.cve_id}><td><Link className="link" href={`/cves/${cve.cve_id}`}>{cve.cve_id}</Link></td><td>{cve.title ?? "Untitled"}</td><td>{formatPct(cve.epss_score)}</td><td>{formatPct(cve.epss_percentile)}</td></tr>)}</tbody></table></div>}</section>; }
export function KevTable({ cves }: { cves: KevCve[] | null | undefined }) { const rows = cves ?? []; return <section className="card"><h2 className="text-lg font-semibold">Known Exploited Vulnerabilities</h2>{rows.length === 0 ? <p className="empty-state mt-4">No CISA KEV CVEs are available.</p> : <div className="mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>CVE</th><th>Product</th><th>Severity</th><th>EPSS</th><th>CVSS</th><th>Required action</th><th>Due date</th></tr></thead><tbody>{rows.map((cve) => <tr key={cve.cve_id}><td><Link className="link" href={`/cves/${cve.cve_id}`}>{cve.cve_id}</Link></td><td>{cve.product ?? "Unknown"}</td><td>{cve.severity ?? "Unknown"}</td><td>{formatPct(cve.epss_score)}</td><td>{formatCvss(cve.cvss_score)}</td><td title={cve.required_action ?? undefined}>{formatTruncated(cve.required_action)}</td><td>{cve.due_date ?? "—"}</td></tr>)}</tbody></table></div>}</section>; }
export function DataSourcesPanel({ stats }: { stats: Stats }) { return <section className="card"><h2 className="text-lg font-semibold">Data Sources</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Microsoft MSRC", stats.total_cves], ["NVD", stats.nvd_enriched_cves], ["FIRST EPSS", stats.epss_enriched_cves], ["CISA KEV", stats.total_kev_vulnerabilities]].map(([label, count]) => <div key={label as string} className="rounded-2xl border border-slate-800 bg-slate-950/60 p-4"><div className="flex items-center justify-between"><span className="font-semibold">{label}</span><span className={`h-2.5 w-2.5 rounded-full ${safeNumber(count as number) > 0 ? "bg-emerald-400" : "bg-slate-600"}`} /></div><p className="mt-2 text-sm text-slate-400">{formatCount(count as number)} records matched</p></div>)}</div></section>; }
