import { getJson } from "../../../src/api";
import AiContextPanel from "./AiContextPanel";

type ProductRow = { id?: number | string; product?: { name?: string | null; product_id?: string | null } | null; severity?: string | null; impact?: string | null; cvss_base_score?: number | null; cvss_vector?: string | null; product_family?: string | null; product_category?: string | null };
type RemediationRow = { id?: number | string; product?: { name?: string | null } | null; description?: string | null; url?: string | null; type?: string | null; sub_type?: string | null };
type CveDetail = Record<string, any> & { cve_id: string; title?: string | null; description?: string | null; affected_products?: ProductRow[] | null; remediations?: RemediationRow[] | null };
type AiContext = { plain_summary: string; business_impact: string; who_should_act: string[]; what_to_check: string[]; recommended_action: string; limitations: string[] };
function pct(value: number | null | undefined) { return value == null ? "—" : `${(value * 100).toFixed(1)}%`; }
function score(value: number | null | undefined) { return value == null ? "—" : value.toFixed(1); }
function Text({ value }: { value: unknown }) { return <>{typeof value === "string" && value.trim() ? value : "—"}</>; }
function SummaryCard({ label, value, helper, tone = "text-white" }: { label: string; value: React.ReactNode; helper?: React.ReactNode; tone?: string }) { return <div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-4"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${tone}`}>{value}</p>{helper ? <p className="mt-1 text-xs text-slate-400">{helper}</p> : null}</div>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="empty-state mt-3">{children}</p>; }

export default async function CveDetails({ params }: { params: Promise<{ cve_id: string }> }) {
  const { cve_id } = await params;
  const cve = await getJson<CveDetail>(`/cves/${cve_id}`, { cve_id, affected_products: [], remediations: [] });
  const aiContext = await getJson<AiContext | null>(`/cves/${cve_id}/ai-context`, null);
  const products = cve.affected_products ?? [];
  const remediations = cve.remediations ?? [];
  const releaseName = cve.release?.release_name ?? cve.release_name ?? null;
  const cvss = cve.nvd_cvss_score ?? cve.cvss_score ?? null;
  return <article className="space-y-6"><header className="rounded-3xl border border-cyan-400/20 bg-slate-900/80 p-6"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">CVE Detail</p><h1 className="mt-2 text-3xl font-black tracking-tight">{cve.cve_id}</h1><p className="mt-2 max-w-4xl text-slate-300">{cve.title ?? "Untitled vulnerability"}</p></header>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><SummaryCard label="Severity" value={cve.severity ?? "Unknown"} tone="text-rose-200" /><SummaryCard label="CVSS" value={score(cvss)} helper={cve.nvd_cvss_score == null ? "MSRC score or unavailable" : "NVD CVSS"} tone="text-cyan-200" /><SummaryCard label="EPSS" value={pct(cve.epss_score)} helper={`Percentile ${pct(cve.epss_percentile)}`} tone="text-orange-200" /><SummaryCard label="KEV" value={cve.kev_known_exploited ? "Listed" : "Not listed"} helper={cve.kev_due_date ? `Due ${cve.kev_due_date}` : "CISA KEV status"} tone={cve.kev_known_exploited ? "text-red-300" : "text-slate-300"} /><SummaryCard label="Release" value={releaseName ?? "—"} helper="MSRC release" /></section>
    <AiContextPanel cveId={cve.cve_id} initialContext={aiContext} />
    <section className="card"><h2 className="text-xl font-semibold">MSRC</h2><p className="mt-3 text-slate-300">{cve.description ?? "No MSRC description loaded yet."}</p><div className="mt-4 grid gap-3 md:grid-cols-3"><p className="rounded-xl bg-slate-950/70 p-3 text-sm"><span className="text-slate-500">Exploited:</span> {cve.exploited ? "Yes" : "No"}</p><p className="rounded-xl bg-slate-950/70 p-3 text-sm"><span className="text-slate-500">Publicly disclosed:</span> {cve.publicly_disclosed ? "Yes" : "No"}</p><p className="rounded-xl bg-slate-950/70 p-3 text-sm"><span className="text-slate-500">Impact:</span> <Text value={cve.impact} /></p></div></section>
    <section className="grid gap-4 lg:grid-cols-3"><div className="card"><h2 className="font-semibold text-emerald-300">NVD</h2>{cve.nvd_cvss_score == null ? <Empty>No NVD CVSS enrichment available.</Empty> : <div className="mt-3 space-y-2 text-sm"><p>CVSS: {score(cve.nvd_cvss_score)}</p><p>Vector: <Text value={cve.nvd_cvss_vector} /></p><p>Severity: <Text value={cve.nvd_severity} /></p></div>}</div><div className="card"><h2 className="font-semibold text-blue-300">FIRST EPSS</h2>{cve.epss_score == null ? <Empty>No EPSS enrichment available.</Empty> : <div className="mt-3 space-y-2 text-sm"><p>Score: {pct(cve.epss_score)}</p><p>Percentile: {pct(cve.epss_percentile)}</p></div>}</div><div className="card"><h2 className="font-semibold text-red-300">CISA KEV</h2>{!cve.kev_known_exploited ? <Empty>This CVE is not listed in the CISA KEV catalog.</Empty> : <div className="mt-3 space-y-2 text-sm"><p>Vendor/project: <Text value={cve.kev_vendor_project} /></p><p>Product: <Text value={cve.kev_product} /></p><p>Due date: <Text value={cve.kev_due_date} /></p><p>Required action: <Text value={cve.kev_required_action} /></p></div>}</div></section>
    <section className="card"><h2 className="text-xl font-semibold">Affected products</h2>{products.length === 0 ? <Empty>No affected products are available for this CVE.</Empty> : <div className="mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>Product</th><th>Family</th><th>Category</th><th>ProductID</th><th>Severity</th><th>Impact</th><th>MSRC CVSS</th><th>Vector</th></tr></thead><tbody>{products.map((p, index) => <tr key={p.id ?? `${p.product?.product_id ?? "product"}-${index}`}><td>{p.product?.name ?? "Unknown product"}</td><td>{p.product_family ?? "Unknown"}</td><td>{p.product_category ?? "Unknown"}</td><td>{p.product?.product_id ?? "—"}</td><td>{p.severity ?? "—"}</td><td>{p.impact ?? "—"}</td><td>{score(p.cvss_base_score)}</td><td>{p.cvss_vector ?? "—"}</td></tr>)}</tbody></table></div>}</section>
    <section className="card"><h2 className="text-xl font-semibold">Remediation</h2>{remediations.length === 0 ? <Empty>No remediation records are available for this CVE.</Empty> : <div className="mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>Product</th><th>Type</th><th>Description</th><th>Link</th></tr></thead><tbody>{remediations.map((r, index) => <tr key={r.id ?? `${r.url ?? "remediation"}-${index}`}><td>{r.product?.name ?? "All / unspecified"}</td><td>{r.type ?? r.sub_type ?? "—"}</td><td>{r.description ?? "—"}</td><td>{r.url ? <a className="link" href={r.url}>Open</a> : "—"}</td></tr>)}</tbody></table></div>}</section></article>;
}
